kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: kafka
  namespace: kafka
spec:
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
