apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: scale-replicas
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["*"]
        resources: ["deployments"]
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: "ApplyConfiguration"
      applyConfiguration:
        expression: |
          Object{
            metadata: Object.metadata {
              labels: Object.metadata.labels {
                mutated: "true"
              }
            },
            spec: Object.spec {
              replicas: 2
            }
          }
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: scale-replicas
spec:
  matchResources:
    matchLabels:
      mutate: test
  policyName: scale-replicas
